steps:
- name: gcr.io/cloud-builders/docker
  args: ['build', '-t', 'gcr.io/sound-yew-347405/ably-project', '--build-arg=JAR_FILE=build/libs/*SNAPSHOT', '.']
images: ['gcr.io/sound-yew-347405/ably-project']
